window.GUILD_MEMBERS = [
  {"name":"Lm폭파/24/max/x2","role":"길드장","image":"guild-members/member-002.jpg","id":"","intro":"돌싱 1년차 연애가능 ＊여친급구＊"},
  {"name":"ᴸᴹ  태리. 22 ᵐᵃˣ ⏩️","role":"부길드장","image":"guild-members/member-001.jpg","id":"","intro":"리미티드 최강전력"},
  {"name":"ᴸᴹ  태초가실분. 22 ᵐᵃˣ ⏩️","role":"운영진","image":"guild-members/member-005.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  팬텀. 24 ᵐᵃˣ ⏩️","role":"운영진","image":"guild-members/member-006.jpg","id":"","intro":"리미티드 길레장인"},
  {"name":"ᴸᴹ  림춘봉. 23 ᵐᵃˣ ⏩️","role":"운영진","image":"guild-members/member-004.jpg","id":"","intro":"리미티드 유일무이 최초 침공 클리어"},
  {"name":"솜이ღ. 21 ¹⁰¹⁰¹⁰⏩️","role":"운영진","image":"guild-members/member-007.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  BunnY  22⁰⁹⁰","role":"운영진","image":"guild-members/member-003.jpg","id":"","intro":"종합가이드 제작자"},
  {"name":"ᴸᴹ  04T. 22 ⁰¹⁰⏩️","role":"길드원","image":"guild-members/member-010.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  ooo더보기. 20 ⁷⁷⁷⏩️","role":"길드원","image":"guild-members/member-011.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  감자. 21 ⁷⁸⁸⏩️","role":"길드원","image":"guild-members/member-012.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  공배기. 21 ⁹⁹⁸ ⏩️","role":"길드원","image":"guild-members/member-013.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  그만키워. 22 ⁰⁰⁰⏩️","role":"길드원","image":"guild-members/member-014.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  깅땅. 20 ⁹⁹⁸⏩️","role":"길드원","image":"guild-members/member-015.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  란츠. 20 ⁰⁰⁰ ⏩️","role":"길드원","image":"guild-members/member-016.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  리쭈리. 18 ⁹⁸⁹⏩️","role":"길드원","image":"guild-members/member-017.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  모카. 23 ⁰⁰⁰","role":"길드원","image":"guild-members/member-018.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  물딜러. 20 ⁷⁷⁸⏩️","role":"길드원","image":"guild-members/member-019.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  민피브. 19 ⁶⁶⁷⏩️","role":"길드원","image":"guild-members/member-020.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  우바잉. 21 ⁰⁹⁹⏩️","role":"길드원","image":"guild-members/member-021.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  이상한콩쥐. 23 ᵐᵃˣ","role":"길드원","image":"guild-members/member-022.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  인디(천사). 20 ⁸⁸⁹⏩️","role":"길드원","image":"guild-members/member-023.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  조커. 21 ⁰⁰⁹⏩️","role":"길드원","image":"guild-members/member-024.jpg","id":"","intro":""},
  {"name":"ᴸᴹ  태단구. 25 ᵐᵃˣ⏩️","role":"길드원","image":"guild-members/member-025.jpg","id":"","intro":"길드레이드 25억 (곧)"},
  {"name":"ᴸᴹ  튜닝. 25 ᵐᵃˣ⏩️","role":"길드원","image":"guild-members/member-026.jpg","id":"","intro":""},
  {"name":"ᴸᴹ nasa. 22 ᵐᵃˣ ⏩️","role":"길드원","image":"guild-members/member-027.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 구내염짓누르기21 ⁰⁰⁰","role":"길드원","image":"guild-members/member-028.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 꾸레.22 ⁹⁹⁹","role":"길드원","image":"guild-members/member-029.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 미남규. 21 ⁹⁹⁹  ⏩️","role":"길드원","image":"guild-members/member-030.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 선녀사랑. 21⁹⁹⁰  ⏩️","role":"길드원","image":"guild-members/member-031.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 안난진/21/ᵐᵃˣ","role":"길드원","image":"guild-members/member-032.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 초월. 20 ⁸⁸⁹ ⏩️","role":"길드원","image":"guild-members/member-033.jpg","id":"","intro":""},
  {"name":"ᴸᴹ 파츠. 22 ᵐᵃˣ⏩️","role":"길드원","image":"guild-members/member-034.jpg","id":"","intro":"태초귀신"},
  {"name":"ᴸᴹ 폐급손가락.20⁰¹⁰⏩️","role":"길드원","image":"guild-members/member-035.jpg","id":"","intro":""},
  {"name":"Loveღ개굴. 23 ⁰⁰⁰","role":"용병","image":"guild-members/member-008.jpg","id":"","intro":""},
  {"name":"ɪᴛᴇʀ•Jin / 20/ ⁹¹⁰⁹","role":"용병","image":"guild-members/member-009.jpg","id":"","intro":""},
  {"name":"달마/24","role":"용병","image":"guild-members/member-036.jpg","id":"","intro":"방랑자"}
];
