window.GUILD_MEMBERS = [
  { name: "Lm폭파/24/max/x2", role: "길드장", image: "guild-members/member-002.jpg" },
  { name: "ᴸᴹ  태리. 22 ᵐᵃˣ ⏩️", role: "부길드장", image: "guild-members/member-001.jpg" },
  { name: "ᴸᴹ  태초가실분. 22 ᵐᵃˣ ⏩️", role: "운영진", image: "guild-members/member-005.jpg" },
  { name: "ᴸᴹ  팬텀. 24 ᵐᵃˣ ⏩️", role: "운영진", image: "guild-members/member-006.jpg" },
  { name: "ᴸᴹ  림춘봉. 23 ᵐᵃˣ ⏩️", role: "운영진", image: "guild-members/member-004.jpg" },
  { name: "솜이ღ. 21 ¹⁰¹⁰¹⁰⏩️", role: "운영진", image: "guild-members/member-007.jpg" },
  { name: "ᴸᴹ  BunnY  22⁰⁹⁰", role: "길드원", image: "guild-members/member-003.jpg" },
  { name: "Loveღ개굴. 23 ⁰⁰⁰", role: "길드원", image: "guild-members/member-008.jpg" },
  { name: "ᴸᴹ  04T. 22 ⁰¹⁰⏩️", role: "길드원", image: "guild-members/member-010.jpg" },
  { name: "ᴸᴹ  ooo더보기. 20 ⁷⁷⁷⏩️", role: "길드원", image: "guild-members/member-011.jpg" },
  { name: "ᴸᴹ  감자. 21 ⁷⁸⁸⏩️", role: "길드원", image: "guild-members/member-012.jpg" },
  { name: "ᴸᴹ  공배기. 21 ⁹⁹⁸ ⏩️", role: "길드원", image: "guild-members/member-013.jpg" },
  { name: "ᴸᴹ  그만키워. 22 ⁰⁰⁰⏩️", role: "길드원", image: "guild-members/member-014.jpg" },
  { name: "ᴸᴹ  깅땅. 20 ⁹⁹⁸⏩️", role: "길드원", image: "guild-members/member-015.jpg" },
  { name: "ᴸᴹ  란츠. 20 ⁰⁰⁰ ⏩️", role: "길드원", image: "guild-members/member-016.jpg" },
  { name: "ᴸᴹ  리쭈리. 18 ⁹⁸⁹⏩️", role: "길드원", image: "guild-members/member-017.jpg" },
  { name: "ᴸᴹ  모카. 23 ⁰⁰⁰", role: "길드원", image: "guild-members/member-018.jpg" },
  { name: "ᴸᴹ  물딜러. 20 ⁷⁷⁸⏩️", role: "길드원", image: "guild-members/member-019.jpg" },
  { name: "ᴸᴹ  민피브. 19 ⁶⁶⁷⏩️", role: "길드원", image: "guild-members/member-020.jpg" },
  { name: "ᴸᴹ  우바잉. 21 ⁰⁹⁹⏩️", role: "길드원", image: "guild-members/member-021.jpg" },
  { name: "ᴸᴹ  이상한콩쥐. 23 ᵐᵃˣ", role: "길드원", image: "guild-members/member-022.jpg" },
  { name: "ᴸᴹ  인디(천사). 20 ⁸⁸⁹⏩️", role: "길드원", image: "guild-members/member-023.jpg" },
  { name: "ᴸᴹ  조커. 21 ⁰⁰⁹⏩️", role: "길드원", image: "guild-members/member-024.jpg" },
  { name: "ᴸᴹ  태단구. 25 ᵐᵃˣ⏩️", role: "길드원", image: "guild-members/member-025.jpg" },
  { name: "ᴸᴹ  튜닝. 25 ᵐᵃˣ⏩️", role: "길드원", image: "guild-members/member-026.jpg" },
  { name: "ᴸᴹ nasa. 22 ᵐᵃˣ ⏩️", role: "길드원", image: "guild-members/member-027.jpg" },
  { name: "ᴸᴹ 구내염짓누르기21 ⁰⁰⁰", role: "길드원", image: "guild-members/member-028.jpg" },
  { name: "ᴸᴹ 꾸레.22 ⁹⁹⁹", role: "길드원", image: "guild-members/member-029.jpg" },
  { name: "ᴸᴹ 미남규. 21 ⁹⁹⁹  ⏩️", role: "길드원", image: "guild-members/member-030.jpg" },
  { name: "ᴸᴹ 선녀사랑. 21⁹⁹⁰  ⏩️", role: "길드원", image: "guild-members/member-031.jpg" },
  { name: "ᴸᴹ 안난진/21/ᵐᵃˣ", role: "길드원", image: "guild-members/member-032.jpg" },
  { name: "ᴸᴹ 초월. 20 ⁸⁸⁹ ⏩️", role: "길드원", image: "guild-members/member-033.jpg" },
  { name: "ᴸᴹ 파츠. 22 ᵐᵃˣ⏩️", role: "길드원", image: "guild-members/member-034.jpg" },
  { name: "ᴸᴹ 폐급손가락.20⁰¹⁰⏩️", role: "길드원", image: "guild-members/member-035.jpg" },
  { name: "ɪᴛᴇʀ•Jin / 20/ ⁹¹⁰⁹", role: "용병", image: "guild-members/member-009.jpg" },
  { name: "달마/24", role: "용병", image: "guild-members/member-036.jpg" }
];
